spring:
  banner:
    location: classpath:banner.txt
  config:
    import: optional:configserver:${CONFIG_URL:http://localhost:8888/}
  profiles:
    active: ${PROFILE}
  cloud:
    config:
      name: ioj
